"use client";

import Link from "next/link";
import { useAdvisorContext } from "./advisor";
import { LanguageSelector, useLanguage } from "./i18n";
export default function Home() {
  const { openAdvisor } = useAdvisorContext();
  const { t } = useLanguage();
  const features = [
    { number: "01", label: "BUSINESS FINDER", title: "Don't have a business idea yet?", body: "Discover opportunities shaped around your budget, location, interests, and preferences.", items: ["Budget", "Location", "Interests"], href: "/finder", cta: "Explore Finder" },
    { number: "02", label: "BUSINESS PLANNER", title: "Already have an idea?", body: "Pressure-test it with research across demand, competition, economics, customer fit, and risk.", items: ["Market demand", "Startup economics", "Risks & opportunities"], href: "/planner", cta: "Analyze an Idea" },
    { number: "03", label: "AI ADVISOR", title: "Need help making the decision?", body: "Ask contextual follow-up questions about your venture and analysis with your decision partner.", items: ["Contextual guidance", "Follow-up questions", "Clear next steps"], href: "#advisor", cta: "Ask the Advisor" },
  ];
  return <main className="site-shell landing-page">
    <nav className="topbar"><Link className="brand" href="/"><span className="brand-mark">V</span><span>VentureForge</span></Link><div className="nav-links"><Link className="active" href="/">{t("home")}</Link><Link href="/finder">{t("finder")}</Link><Link href="/planner">{t("planner")}</Link><LanguageSelector /></div><span className="status-pill"><span className="status-dot" /> {t("online")}</span></nav>

    <section className="landing-hero"><div className="landing-copy"><p className="eyebrow"><span /> {t("platform")}</p><h1 dangerouslySetInnerHTML={{ __html: t("homeHero") }} /><p className="landing-lede">{t("landingLede")}</p><div className="hero-actions"><Link className="landing-primary" href="/finder">{t("findBusinessIdea")} <span>→</span></Link><Link className="landing-secondary" href="/planner">{t("analyzeMyIdea")} <span>→</span></Link></div><p className="hero-note"><span className="status-dot" /> {t("researchBacked")}</p></div><div className="signal-visual landing-signal-visual" aria-label="Animated VentureForge intelligence visual"><div className="signal-ring ring-one" /><div className="signal-ring ring-two" /><span>VF</span><i /></div></section>

    <section className="feature-section landing-features"><div className="landing-section-intro"><p className="eyebrow"><span /> {t("threeWays")}</p><h2>{t("uncertainty")}</h2></div><div className="landing-feature-grid">{features.map((feature) => <article className="landing-feature" id={feature.number === "03" ? "advisor" : undefined} key={feature.number}><div className="feature-topline"><span>{feature.number}</span><p>{feature.number === "01" ? t("finderKicker") : feature.number === "02" ? t("plannerKicker") : t("advisorLabel")}</p></div><h3>{feature.number === "01" ? t("dontHave") : feature.number === "02" ? t("alreadyHave") : t("needHelp")}</h3><p className="feature-body">{feature.number === "01" ? t("discover") : feature.number === "02" ? t("pressure") : t("contextual")}</p><ul>{feature.number === "01" ? [t("budget"), t("location"), t("interests")].map((item) => <li key={item}><span>+</span>{item}</li>) : feature.number === "02" ? [t("marketDemand"), t("startupEconomics"), t("riskOpportunity")].map((item) => <li key={item}><span>+</span>{item}</li>) : [t("contextGuidance"), t("followUp"), t("clearSteps")].map((item) => <li key={item}><span>+</span>{item}</li>)}</ul>{feature.number === "03" ? <button className="landing-feature-action" type="button" onClick={openAdvisor}>{t("advisor")} <span>→</span></button> : <Link href={feature.href}>{feature.number === "01" ? t("exploreFinder") : t("analyzeIdea")} <span>→</span></Link>}</article>)}</div></section>

    <section className="how-section"><div className="how-heading"><p className="eyebrow"><span /> {t("method")}</p><h2>{t("process")}</h2></div><div className="how-steps">{[["01", t("tellConsidering"), t("ideaLocation")], ["02", t("letResearch"), t("researchScope")], ["03", t("smarter"), t("clearDecision")]].map(([number, title, body]) => <article className="how-step" key={number}><span>{number}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></section>

    <section className="preview-section"><div className="preview-copy"><p className="eyebrow"><span /> {t("productPreview")}</p><h2>{t("clarity")}</h2><p>{t("previewCopy")}</p><Link className="text-link" href="/planner">{t("seeWorks")} <span>→</span></Link></div><div className="preview-card"><div className="preview-header"><div><p className="card-kicker">{t("analysisComplete")}</p><h3>{t("preview")}</h3></div><span className="preview-badge">{t("demo")}</span></div><div className="preview-score"><div><p>{t("overall")}</p><strong>7.8<small>/10</small></strong></div><div><p>{t("decision")}</p><b>GO</b></div></div><div className="preview-bars">{[[t("marketDemand"), "8/10", "80%"], [t("marketGap"), "8/10", "80%"], [t("competition"), "7/10", "70%"], [t("financialFeasibility"), "9/10", "90%"], [t("riskLevel"), "7/10", "70%"]].map(([label, score, width]) => <div key={label}><span>{label}</span><b>{score}</b><i><em style={{ width }} /></i></div>)}</div><p className="preview-quote">“{t("evidence")}”</p><span className="preview-disclaimer">{t("illustrative")}</span></div></section>

    <section className="closing-section"><p className="eyebrow"><span /> {t("yourNext")}</p><h2>{t("deserves")}</h2><p>{t("exploreRisks")}</p><div className="hero-actions"><Link className="landing-primary" href="/finder">{t("findBusinessIdea")} <span>→</span></Link><Link className="landing-secondary" href="/planner">{t("analyzeMyIdea")} <span>→</span></Link></div></section>
    <footer><span>VENTUREFORGE / 2026</span><span>{t("built")}</span></footer>
  </main>;
}
